server:
  port: 9001

spring:
  datasource:
    url: 'jdbc:postgresql://94.73.130.42:5432/forexampal'
    username: usr_fep
    password: '220750Aa.'
    hikari:
      max-lifetime: 1200000
      idle-timeout: 600000
      connection-timeout: 40000
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: sch_fep
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: postgres
  sql:
    init:
      platform: postgres
  liquibase:
    enabled: false
    user: usr_fep
    password: '220750Aa.'
    change-log: classpath:db/changelog/master.changelog.xml
    default-schema: sch_fep
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    always-use-message-format: false
    basename: messages/messages
    cache-duration: -1
    encoding: UTF-8
    fallback-to-system-locale: true